---
abstract: 'access Google Keep notes from Perl'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Google-Keep
no_index:
  directory:
    - t
    - inc
requires:
  Encode: '0'
  Filter::signatures: '0.1'
  Future::HTTP: '0'
  JSON: '0'
  Moo: '2'
  URI::URL: '0'
  WWW::Mechanize::Chrome: '0'
  perl: '5.006'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Net-Google-Keep
  license: http://dev.perl.org/licenses/
  repository: git://github.com/Corion/Net-Google-Keep.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
